j100_0000:
  ekf_map:
    ros__parameters:
      frequency: 50.0
      sensor_timeout: 0.1
      two_d_mode: true
      publish_tf: true
      map_frame: world
      odom_frame: odom
      base_link_frame: base_link
      world_frame: world

      odom0: platform/odom
      odom0_config: [false, false, false, false, false, false,
                     false, false, false, false, false, false,
                     false, false, false]

      imu0: sensors/imu_0/data
      imu0_config: [false, false, false, false, false, false,
                    false, false, false, false, false,
                    true, true, false, false]

      use_control: false
      print_diagnostics: true
      debug: false