j100_0000:
  navsat_transform:
    ros__parameters:
      use_odometry_yaw: true
      yaw_offset: 0.0
      zero_altitude: true
      broadcast_utm_transform: true
      publish_filtered_gps: true
      use_control: false

      gps_topic: sensors/gps_1/fix
      imu_topic: sensors/gps_1/imu/data
      odometry_topic: platform/odom