"""
Jackal Sensors Launch file. Autogenerated by Clearpath Common

Modified by Will Solow, 2025
"""

from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, DeclareLaunchArgument, ExecuteProcess
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import EnvironmentVariable, FindExecutable, PathJoinSubstitution, LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from ament_index_python.packages import get_package_prefix, get_package_share_directory
import os 

def generate_launch_description():

    # Include Packages
    pkg_jackal_description = get_package_share_directory("jackal_description")

    # Declare launch files
    launch_file_lidar_2d_0 = os.path.join(pkg_jackal_description, "launch/sensors/launch/lidar_2d_0.launch.py")
    launch_file_axis_camera_0 = os.path.join(pkg_jackal_description, "launch/sensors/launch/axis_camera_0.launch.py")

    # Include launch files
    launch_lidar_2d_0 = IncludeLaunchDescription(
        PythonLaunchDescriptionSource([launch_file_lidar_2d_0]),
    )
    launch_axis_camera_0 = IncludeLaunchDescription(
        PythonLaunchDescriptionSource([launch_file_axis_camera_0]),
    )

    # Create LaunchDescription
    ld = LaunchDescription()
    ld.add_action(launch_lidar_2d_0)
    ld.add_action(launch_axis_camera_0)
    return ld
