- ros_topic_name: sensors/imu_1/data
  gz_topic_name: /j100_0000/sensors/imu_1/data
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS
- ros_topic_name: sensors/imu_1/data_raw
  gz_topic_name: /j100_0000/sensors/imu_1/data_raw
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS