- ros_topic_name: sensors/lidar2d_0/scan
  gz_topic_name: /j100_0000/sensors/lidar2d_0/scan
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserSacn
  direction: GZ_TO_ROS
- ros_topic_name: sensors/lidar2d_0/scan/points
  gz_topic_name: /j100_0000/sensors/lidar2d_0/scan/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS